src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use \Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @Vich\Uploadable()
 */

class Property
{
    const NBRPORTE=[
        4=>'4 wheel drivers',
        2=>'sport',
        6=>'limousine 6 Dors'
    ];
    const CARCONDITION=[
        1=>'Used',
        2=>'New'
    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var File | null
     * @Assert\Image(
     *     mimeTypes={"image/jpeg", "image/jpg", "image/png"})
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="fileName")
     */
    private $imageFile;

    /**
     * @var string | null
     * @ORM\Column(type="string", length=255)
     */
    private $fileName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $couleur;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $annee;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbrporte;

    /**
     *
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $model;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fabricant;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publish_at;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $kilometer;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $carCondition;

    /**
 * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
 */
    private $Options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin", inversedBy="properties")
     */
    private $admin;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Client", inversedBy="client_properties")
     */
    private $client;

    public function __construct()
    {
        $this->publish_at = new \DateTime();
        $this->Options = new ArrayCollection();
        $this->client = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function getSlug() : string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(?string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getAnnee(): ?int
    {
        return $this->annee;
    }

    public function setAnnee(?int $annee): self
    {
        $this->annee = $annee;

        return $this;
    }

    public function getNbrporte(): ?int
    {
        return $this->nbrporte;
    }

    public function setNbrporte(?int $nbrporte): self
    {
        $this->nbrporte = $nbrporte;

        return $this;
    }

    public function getBodyType(): string
    {
        return self::NBRPORTE[$this->nbrporte];
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormatPrice() : string
    {
        return number_format($this->price,0,'',' ');

    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getFabricant(): ?string
    {
        return $this->fabricant;
    }

    public function setFabricant(string $fabricant): self
    {
        $this->fabricant = $fabricant;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getPublishAt(): ?\DateTimeInterface
    {
        return $this->publish_at;
    }

    public function setPublishAt(\DateTimeInterface $publish_at): self
    {
        $this->publish_at = $publish_at;

        return $this;
    }

    public function getKilometer(): ?int
    {
        return $this->kilometer;
    }

    public function setKilometer(?int $kilometer): self
    {
        $this->kilometer = $kilometer;

        return $this;
    }
    public function getFormatKilometer() : string
    {
        return number_format($this->kilometer,0,'',' ');

    }

    /**
     * @return mixed
     */
    public function getCarCondition()
    {
        return $this->carCondition;
    }

    /**
     * @param mixed $carCondition
     * @return Property
     */
    public function setCarCondition($carCondition)
    {
        $this->carCondition = $carCondition;
        return $this;
    }




    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->Options;
    }

    public function addOption(Option $options): self
    {
        if (!$this->Options->contains($options)) {
            $this->Options[] = $options;
            $options->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $options): self
    {
        if ($this->Options->contains($options)) {
            $this->Options->removeElement($options);
            $options->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param null| File $imageFile
     * @return Property
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;
        if($this->imageFile instanceof File){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    /**
     * @return string|null
     */
    public function getFileName(): ?String
    {
        return $this->fileName;
    }

    /**
     * @param null |string $fileName
     * @return Property
     */
    public function setFileName(?String $fileName): Property
    {
        $this->fileName = $fileName;
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getAdmin(): ?Admin
    {
        return $this->admin;
    }

    public function setAdmin(?Admin $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    /**
     * @return Collection|Client[]
     */
    public function getClient(): Collection
    {
        return $this->client;
    }

    public function addClient(Client $client): self
    {
        if (!$this->client->contains($client)) {
            $this->client[] = $client;
        }

        return $this;
    }

    public function removeClient(Client $client): self
    {
        if ($this->client->contains($client)) {
            $this->client->removeElement($client);
        }

        return $this;
    }


}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('couleur')
            ->add('annee')
            ->add('nbrporte',ChoiceType::class, [
                'choices'=> $this->getChoices()
            ])
            ->add('options', EntityType::class, [
                'class'=>Option::class,
                'choice_label'=>'name',
                'multiple'=>true
            ])
            ->add('imageFile', FileType::class, [
                'required'=> false
            ])
            ->add('price')
            ->add('city')
            ->add('model')
            ->add('fabricant')
            ->add('sold')
            ->add('kilometer')
            ->add('carCondition',ChoiceType::class, [
                'choices'=> $this->getCarCondition()
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain'=>'forms',
        ]);
    }

    private function getChoices()
    {
        $choices = Property::NBRPORTE;
        $output = [];
        foreach ($choices as $k => $v){
            $output[$v] = $k;
        }
        return $output;
    }

    private function getCarCondition()
    {
        $choices = Property::CARCONDITION;
        $output = [];
        foreach ($choices as $k => $v){
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php
namespace App\Controller;
use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine \ ORM \ EntityManagerInterface;

class PropertyController extends AbstractController
{

    /**
     * @var PropertyRepository
     */
    private PropertyRepository $repository;
    /**
     * @var EntityManagerInterface
     */
    private EntityManagerInterface $em;


    public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
    {

        $this->repository = $repository;

        $this->em = $em;
    }

    /**
     * @Route("/cars", name="property.index")
     * @return Response
     */
    public  function index(PaginatorInterface $paginator, Request $request): Response
    {

        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page',1),
            6
        );

        $client = $this->getUser();

        return $this->render('property/index.html.twig', [
            'current_menu'=>'properties',
            'properites'=> $properties,
            'form'=> $form->createView(),
            "client"=> $client
        ]);
    }

    /**
     * @Route("/cars/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Property $property
     * @return Response
     */

    public function show(Property $property, string $slug, Request $request, ContactNotification $notification) : Response
    {

        $client = $this->getUser();
        if($property->getSlug() !== $slug){
            return $this->redirectToRoute('property.show',[
                'id' => $property->getId(),
                'slug'=> $property->getSlug()
            ], 301);
        }
        $contact = new Contact();
        $form = $this->createForm(ContactType::class);
        $contact->setProperty($property);
        $form->handleRequest($request);

        if($form->isSubmitted() and $form->isValid()){
            $notification->notify($contact);
            $this->addFlash('success','Your Email has been successfully Send ');
            return $this->redirectToRoute(
                'property.show',[
                    'id' => $property->getId(),
                    'slug'=> $property->getSlug()
                ]);
        }
        return $this->render('property/show.html.twig', [
            "property"=> $property,
            "current_menu" => "properties",
            "client"=> $client,
            "form"=> $form->createView()
        ]);
    }


}

templates/property/_property.html.twig
<div class="card mb-4">
    {% if property.fileName %}
        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;">
        {% else %}
            <img src="{{ 'images/properties/avatar.png' | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;">
    {% endif %}
    <div class="card-body">
        <h5 class="card-tittle">
            <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">
                {{ property.fabricant }} {{ property.model }}
            </a>
        </h5>
        <p class="card-text">
            {{ property.city }}
        </p>
        <div class="text-primary" style="font-size: 2rem; font-weight: bold;">
            {{ property.formatPrice }} $
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Voire toutes nos voitures' %}
{% block body %}
    <div class="row">
        <div class="col-md-3">
            <div class="jumbotron  mt-4">
                <h3>Customize Search</h3>
                <div class="container">
                    {{ form_start(form) }}
                    <div class="form-row">
                        <div class="row">
                            <div class="col-md-6">
                                {{ form_row(form.fabricant) }}
                            </div>
                            <div class="col-md-6">
                                {{ form_row(form.model) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                {{ form_row(form.options) }}
                            </div>
                            <div class="col-md-6">
                                {{ form_row(form.carCondition) }}
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                {{ form_row(form.minKilometer) }}
                            </div>
                            <div class="col-md-6">
                                {{ form_row(form.maxKilometer) }}
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                {{ form_row(form.minPrice) }}
                            </div>
                            <div class="col-md-6">
                                {{ form_row(form.maxPrice) }}
                            </div>

                        </div>


                    </div>
                    <div class="col">
                        {{ form_row(form.sortby) }}
                        <button class="btn btn-primary">Search</button>
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>

        <div class="col-md-9">
            <div class="container mt-4">
                <div class="jumbotron text-left">
                    <h3>Brand New Cars</h3>
                    <div class="row">
                        {%  for property in properites %}
                            <div class="col-md-4">
                                {% include 'property/_property.html.twig' %}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="pagination">
                        {{ knp_pagination_render(properites) }}
                    </div>
                </div>
            </div>
        </div>
    </div>



 {% endblock  %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}
{% block title property.title %}
{% block body %}
    <div class="jumbotron">
        <div class="container mt-4">
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}

            <div class="row">
                <div class="col-md-8">
                    {% if property.fileName %}
                        <img src="{{ vich_uploader_asset(property, 'imageFile')  }}" alt="card-img-top" style="width: 100%; height: auto;">
                    {% else %}
                        <img src="{{ 'images/properties/avatar.png'  }}" alt="card-img-top" style="width: 100%; height: auto;">
                    {% endif %}
                </div>
                <div class="col-md-4">

                    <h1>{{ property.fabricant }}   {{ property.model }}</h1>
                    <div class="text-primary" style="font-size: 4rem; font-weight: bold">{{ property.formatPrice }} $</div>
                    <a href="#" class="btn btn-primary">Contact Us</a> <a href="{{ path('client.favorite', {id: property.id, slug: property.slug}) }}" class="btn btn-danger">Add To Favorite</a>
                    <div id="contactForm" class="mt-4">
                        {{ form_start(form) }}
                        <div class="row">
                            <div class="col">{{ form_row(form.firstname) }}</div>
                            <div class="col">{{ form_row(form.lastname) }}</div>
                        </div>
                        <div class="row">
                            <div class="col">{{ form_row(form.phone) }}</div>
                            <div class="col">{{ form_row(form.email) }}</div>
                        </div>
                        {{ form_rest(form) }}
                        <div class="form-group">
                            <button class="btn btn-primary">Send</button>
                        </div>
                        {{ form_end(form) }}

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">

       <p>
           <h4>{{ property.description | nl2br }}</h4>  <h1>{{ property.title }}</h1>
       </p>
        <div class="row">
            <div class="col-md-8">
                <h2> About {{ property.fabricant }} {{ property.model }} </h2>
                <table class="table table-striped">
                    <tr>
                        <td>Body type</td>
                        <td>{{ property.bodyType }}</td>
                    </tr>
                    <tr>
                        <td>Year</td>
                        <td>{{ property.annee }}</td>
                    </tr>
                    <tr>
                        <td>Color</td>
                        <td>{{ property.couleur }}</td>
                    </tr>
                    <tr>
                        <td>City</td>
                        <td>{{ property.city }}</td>
                    </tr>

                    <tr>
                        <td>Kilometer</td>
                        <td>{{ property.formatKilometer }} Km</td>
                    </tr>
                    <tr>
                        <td>Condition</td>
                        {% if property.carCondition == 1  %}
                        <td>Used</td>
                        {% else  %}
                        <td>New</td>
                        {% endif %}
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Specificity</h2>
                <ul class="list-group">
                {% for option in property.options %}
                    <li class="list-group-item">
                        {{ option.name }}
                    </li>
                {% endfor %}
                </ul>
            </div>
        </div>

    </div>
{% endblock %}