src/Entity/Client.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClientRepository")
 * @UniqueEntity(fields={"email"}, message="This email is already registred")
 * @UniqueEntity(fields={"username"}, message="This username is already taken")
 */
class Client implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $surname;

    /**
     * @ORM\Column(type="date")
     */
    private $birthDate;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, unique=true)
     */
    private $username ;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Property", mappedBy="client")
     */
    private $client_properties;

    public function __construct()
    {
        $this->client_properties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }
    public function getSlug() : string
    {
        return (new Slugify())->slugify($this->username);
    }

    /**
     * @return Collection|Property[]
     */
    public function getClientProperties(): Collection
    {
        return $this->client_properties;
    }

    public function addClientProperty(Property $clientProperty): self
    {
        if (!$this->client_properties->contains($clientProperty)) {
            $this->client_properties[] = $clientProperty;
            $clientProperty->addClient($this);
        }

        return $this;
    }

    public function removeClientProperty(Property $clientProperty): self
    {
        if ($this->client_properties->contains($clientProperty)) {
            $this->client_properties->removeElement($clientProperty);
            $clientProperty->removeClient($this);
        }

        return $this;
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            ->add('name')
            ->add('surname')
            ->add('password', RepeatedType::class, array(
                'type'=> PasswordType::class,
                'first_options'=> array('label'=>'Password'),
                'second_options'=> array('label'=>'Repeat Password'),
            ))
            ->add('birthDate')
            ->add('tel')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/Client/ClientProperty.php
<?php
namespace App\Controller\Client;
use App\Entity\Client;
use App\Entity\Property;
use App\Repository\ClientRepository;
use Doctrine\ORM\EntityManagerInterface;
use \Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ClientProperty extends AbstractController {


    /**
     * @var ClientRepository
     */
    private ClientRepository $repository;
    /**
     * @var EntityManagerInterface
     */
    private EntityManagerInterface $em;

    public function __construct(ClientRepository $repository, EntityManagerInterface $em)
    {

        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/profile/{slug}-{id}", name="client.profile",  requirements={"slug": "[a-z0-9\-]*"})
     * @param Client $client
     * @param string $slug
     * @return \Symfony\Component\HttpFoundation\Response
     */

    public  function profile(Client $client, string $slug){
        if($client->getSlug() !== $slug){
            return $this->redirectToRoute('client.profile',[
                'id' => $client->getId(),
                'slug'=> $client->getSlug()
            ], 301);
        }

        return $this->render('client/profile.html.twig', [
            "client"=> $client,
            "current_menu" => "properties"
        ]);
    }

    /**
     * @Route("profile/favorite/{slug}-{id}", name="client.favorite", requirements={"slug": "[a-z0-9\-]*"})
     * @param Property $property
     * @param Request $request
     * @return Response
     */
    public function addFavorite(Property $property, Request $request) : Response
    {
        $client = $this->getUser();
        if($this->getUser()){
            $client->addClientProperty($property);
            $this->em->flush();
            $this->addFlash('success', 'The car is added to your favorites');
            return $this->redirectToRoute('property.show', [
                'id' => $client->getId(),
                'slug'=> $client->getSlug()
            ]);
        }
        else{
            $this->addFlash('success', 'This action require to be logged first');
            return $this->redirectToRoute('user.login');
        }


    }


    /**
     * @Route("profile/favorite/{id}", name="favorite.remove")
     * @param Property $property
     * @param Request $request
     * @return Response
     */
    public function removeFavorite(Property $property, Request $request) : Response
    {
        $client = $this->getUser();
        if($this->getUser()){
            $client->removeClientProperty($property);
            $this->em->flush();
            $this->addFlash('success', 'The item has been removed properly');
            return $this->redirectToRoute('client.profile', [
                'id' => $property->getId(),
                'slug'=> $property->getSlug()
            ]);
        }
        else{
            $this->addFlash('success', 'This action require to be logged first');
            return $this->redirectToRoute('user.login');
        }


    }


}

templates/client/profile.html.twig
{% extends 'base.html.twig' %}
{% block title client.username %}
{% block body %}
    <div class="jumbotron">
        <div class="container mt-4">
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            <div class="row">
                <div class="col-md-8">

                </div>
                <div class="col-md-4">


                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">


        <div class="row">
            <div class="col-md-8">
                <h2> About {{ client.name }} {{ client.surname }}</h2>
                <table class="table table-striped">
                    <tr>
                        <td>User Name</td>
                        <td>{{ client.username }}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>{{ client.email }}</td>
                    </tr>
                    <tr>
                        <td>Birth Date</td>
                        <td>{{ client.birthDate.format("d/m/Y")}}</td>
                    </tr>
                    <tr>
                        <td>Tel Number</td>
                        <td>{{ client.tel }}</td>
                    </tr>

                </table>
            </div>
            <div class="col-md-4">
                <h2>Basket</h2>

                {% for property in client.clientProperties %}
                    {% if property.sold == 0 %}
                   <div class="container mt-2">
                       <div class="row">
                           <div class="">
                               <div class="list-group list">
                                   <div class="">
                                       <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb')}}" class="pull-left photo" alt="card-img-top" style="width: 100%; height: auto;">
                                       <h4 class="list-group-item-heading name">{{ property.fabricant }}</h4>
                                       <p class="list-group-item-text title"> {{ property.model }}</p>
                                       <div class="text-primary" style= "font-weight: bold; font-size: 2rem;">{{ property.FormatPrice }} $</div>
                                   </div>
                                   <div class="">
                                       <a href="#" class="btn btn-danger">Buy</a> <a href="{{ path('favorite.remove', {id: property.id}) }}" class="btn btn-danger">remove</a>
                                   </div>
                               </div>
                           </div>

                       </div>

                   </div>
                    {% else %}
                        <div class="container mt-2">
                            <div class="row">
                                <div class="">
                                    <div class="list-group list">
                                        <div class="">
                                            <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb')}}" class="pull-left photo" alt="card-img-top" style="width: 100%; height: auto;">
                                            <h4 class="list-group-item-heading name">{{ property.fabricant }}</h4>
                                            <p class="list-group-item-text title"> {{ property.model }}</p>
                                            <div class="text-primary" style= "font-weight: bold; font-size: 2rem;">{{ property.FormatPrice }} $</div>
                                        </div>
                                        <div class="">
                                            <a href="#" class="btn btn-secondary">This item is no longer available</a> <a href="{{ path('favorite.remove', {id: property.id}) }}" class="btn btn-danger">remove</a>
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>

                    {% endif %}
                {% endfor %}
            </div>
        </div>

    </div>
{% endblock %}